/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 /Users/samuelfuller/Downloads/Assets/Head.001.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Head.001.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh geometry={nodes.Head001_1.geometry} material={materials.Skin_} skeleton={nodes.Head001_1.skeleton} />
        <skinnedMesh geometry={nodes.Head001_2.geometry} material={materials.InsideMouth} skeleton={nodes.Head001_2.skeleton} />
        <skinnedMesh geometry={nodes.Head001_3.geometry} material={materials.Teeth} skeleton={nodes.Head001_3.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/Head.001.glb')
